browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: ie
    version: latest
  - name: microsoftedge
    version: latest
sauce_connect: true
loopback: airtap.local
