name: 'Tests: node.js 6 - 10'

on: [pull_request, push]

jobs:
  tests:
    uses: ljharb/actions/.github/workflows/node-majors.yml@main
    with:
      range: '>= 6 < 10'
      command: npm run tests-only

  node:
    name: 'node 6 - 10'
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - run: 'echo tests completed'
